# ~/.config/hypr/hypridle.conf

general {
    # ロックコマンドの指定（重要！）
    lock_cmd = pidof hyprlock || hyprlock

    # サスペンド（スリープ）から復帰した時に実行するコマンド
    after_sleep_cmd = ~/.config/hypr/scripts/display-wake.sh

    # サスペンドする前に実行するコマンド（ここでロックを掛ける）
    before_sleep_cmd = loginctl lock-session
}

# 1. 画面を少し暗くする（例：2.5分）
# ※ brightnessctl がインストールされている前提
listener {
    timeout = 150
    on-timeout = brightnessctl -s set 10
    on-resume = brightnessctl -r
}

# 2. 画面をロックする（例：5分）
# listener {
#     timeout = 300
#     on-timeout = loginctl lock-session
# }

# 3. 画面の電源を切る
listener {
    timeout = 600
    on-timeout = hyprctl dispatch dpms off
    on-resume = ~/.config/hypr/scripts/display-wake.sh
    ignore_inhibit = true
}

# # 4. PC自体をサスペンドする（例：15分）
# listener {
#     timeout = 900
#     on-timeout = systemctl suspend
# }
