#:schema https://yazi-rs.github.io/schemas/yazi.json

[mgr]
show_hidden = true

[opener]
open = [
	{ run = "yazi-open %s1", desc = "Open with the system default", orphan = true, for = "linux" },
]
play = [
	{ run = "yazi-open %s1", desc = "Open with the system default", orphan = true, for = "linux" },
]
jpegview = [
	{ run = "yazi-open-image %s1", desc = "Open image with JPEGView on WSL", orphan = true, for = "linux" },
]

[open]
prepend_rules = [
	{ mime = "image/*", use = "jpegview" },
]
