#!/usr/bin/env bash

set -euo pipefail

ZETSHELL_SETTINGS_FILE="${ZETSHELL_SETTINGS_FILE:-$HOME/.config/zetshell/settings.env}"

ZETSHELL_SCREENSHOT_DIR_DEFAULT="${XDG_PICTURES_DIR:-$HOME/Pictures}/Screenshots"
ZETSHELL_RECORDINGS_DIR_DEFAULT="${XDG_VIDEOS_DIR:-$HOME/Videos}/Recordings"

ZETSHELL_SCREENSHOT_DIR="${ZETSHELL_SCREENSHOT_DIR:-$ZETSHELL_SCREENSHOT_DIR_DEFAULT}"
ZETSHELL_RECORDINGS_DIR="${ZETSHELL_RECORDINGS_DIR:-$ZETSHELL_RECORDINGS_DIR_DEFAULT}"

if [[ -f "$ZETSHELL_SETTINGS_FILE" ]]; then
    # shellcheck disable=SC1090
    source "$ZETSHELL_SETTINGS_FILE"
fi

export ZETSHELL_SCREENSHOT_DIR
export ZETSHELL_RECORDINGS_DIR
